openapi: 3.0.1
info:
  title: Connector API
  version: 1.0.0
paths:
  /v1/api/accounts/{accountId}/agreements:
    post:
      operationId: createAgreement
      parameters:
      - description: Gateway account ID
        example: 1
        in: path
        name: accountId
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgreementCreateRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgreementResponse'
          description: OK
        "404":
          description: Not found
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Missing required fields
      summary: Create an agreement
  /v1/api/accounts/{accountId}/charges:
    post:
      operationId: createNewCharge
      parameters:
      - description: Gateway account ID
        example: 1
        in: path
        name: accountId
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/ChargeCreateRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargeResponse'
          description: Created
        "400":
          description: Bad Request
        "404":
          description: Not found
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Missing required fields or invalid values
      summary: Create new charge for gateway account
      tags:
      - Charges
  /v1/api/accounts/{accountId}/charges/{chargeId}:
    get:
      operationId: getCharge
      parameters:
      - description: Gateway account ID
        example: 1
        in: path
        name: accountId
        required: true
        schema:
          type: integer
          format: int64
      - description: Charge external ID
        example: b02b63b370fd35418ad66b0101
        in: path
        name: chargeId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargeResponse'
          description: OK
        "404":
          description: Not found
      summary: Get charge by account ID and charge external ID
      tags:
      - Charges
  /v1/api/accounts/{accountId}/telephone-charges:
    post:
      description: "Create a new telephone charge for gateway account. These are externally\
        \ taken payments and the outcome is reported to this endpoint. provider_id\
        \ is used as an idempotency key for API calls. If a payment already exists\
        \ with the provider_id provided, the API will not store a record about a new\
        \ payment, or update or change the record about a payment previously stored."
      operationId: createNewTelephoneCharge
      parameters:
      - description: Gateway account ID
        example: 1
        in: path
        name: accountId
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/TelephoneChargeCreateRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargeResponse'
          description: OK - returns existing charge for provider_id
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargeResponse'
          description: Created
        "403":
          content:
            application/json:
              schema:
                type: string
                example:
                  error_identifier: TELEPHONE_PAYMENT_NOTIFICATIONS_NOT_ALLOWED
                  message:
                  - Telephone payment notifications are not enabled for this gateway
                    account
          description: Forbidden
        "404":
          description: Not found
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Missing required fields or invalid values
      summary: Create a new telephone charge for gateway account.
      tags:
      - Charges
  /v1/api/card-types:
    get:
      operationId: getCardTypes
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardTypesResponse'
          description: OK
      summary: List all card types
  /v1/api/charges/gateway_transaction/{gatewayTransactionId}:
    get:
      operationId: getChargeForGatewayTransactionId
      parameters:
      - description: Gateway transaction ID
        example: 5422624d-12b1-4821-8b26-d0383ecf1602
        in: path
        name: gatewayTransactionId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargeResponse'
          description: OK
        "404":
          description: Not found
      summary: Find charge by gateway transaction ID
      tags:
      - Charges
  /v1/tasks/expired-charges-sweep:
    post:
      description: This starts a task to expire the charges with a default window
        of 90 minutes. The default value can be overridden by setting an environment
        variable CHARGE_EXPIRY_WINDOW_SECONDS in seconds. Response of the call will
        tell you how many charges were successfully expired and how many of them failed
        for some reason. This endpoint also expires charges in AWAITING_CAPTURE_REQUEST
        status. The default window is 120 hours. It can be overriden by setting an
        environment variable AWAITING_DELAY_CAPTURE_EXPIRY_WINDOW in seconds. Also
        expires tokens older than the configured TOKEN_EXPIRY_WINDOW_SECONDS.
      operationId: expireCharges
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
                example:
                  expiry-success: 2
                  expiry-failed: 0
          description: OK
      summary: 'Expire charges and tokens '
      tags:
      - Tasks
components:
  schemas:
    Address:
      type: object
      properties:
        city:
          type: string
          example: London
        country:
          type: string
          example: GB
        county:
          type: string
          example: county
        line1:
          type: string
          example: Address line 1
        line2:
          type: string
          example: Address line 2
        postcode:
          type: string
          example: AB1 2CD
    AgreementCreateRequest:
      type: object
      properties:
        description:
          type: string
          example: Description for the paying user describing the purpose of the agreement
        reference:
          type: string
          example: Service agreement reference
        user_identifier:
          type: string
          example: reference for the paying user
      required:
      - description
      - reference
    AgreementResponse:
      type: object
      properties:
        agreement_id:
          type: string
          example: iaouobo39hiv0m2560q45j3p04
        created_date:
          type: string
          format: date-time
          example: 2022-06-27T13:07:57.58Z
        description:
          type: string
          example: Description for the paying user describing the purpose of the agreement
        live:
          type: boolean
        reference:
          type: string
          example: Service agreement reference
        service_id:
          type: string
          example: Service external ID
        user_identifier:
          type: string
          example: reference for the paying user
    Auth3dsData:
      type: object
      properties:
        htmlOut:
          type: string
          description: "Applicable for ePDQ 3DS payments. If the transaction goes\
            \ via the challenge flow, the response contains the additional field HTML_ANSWER\
            \ (from ePDQ) which is a BASE-64 encoded code block"
        issuerUrl:
          type: string
          description: 'Issuer 3DS url to direct users to complete 3DS authentication '
          example: https://3ds-secure-redirect-url.example.org
        md:
          type: string
          description: payment session identifier returned by the card issuer
          example: NnheOml4nhgrnx...pP6oBb3KQqKXiYGL3X8=
        paRequest:
          type: string
          description: Holds 3D secure request data for the issuer.
          example: eNpVUttygjAQ/R...jI+ts3+f4Afk4a3Y
        worldpayChallengeJwt:
          type: string
          description: "When the charge is in status 'AUTHORISATION 3DS REQUIRED'\
            \ state and the 3DS data on the charge contains challenge data, Json Web\
            \ Token is calculated and returned to the frontend."
    AuthorisationSummary:
      type: object
      description: Object containing information about the authentication of the payment
      properties:
        three_d_secure:
          $ref: '#/components/schemas/ThreeDSecure'
    CardExpiryDate:
      type: object
      description: The expiry date of the card the user paid with.
      example: 01/99
      properties:
        fourDigitYear:
          type: string
        twoDigitMonth:
          type: string
        twoDigitYear:
          type: string
    CardTypeEntity:
      type: object
      properties:
        brand:
          type: string
          example: visa
        id:
          type: string
          format: uuid
          example: ac8a3abd-bcfd-4fa6-8905-321ce913e7f5
        label:
          type: string
          example: Visa
        requires3ds:
          type: boolean
        type:
          type: string
          enum:
          - CREDIT
          - DEBIT
          example: DEBIT
    CardTypesResponse:
      type: object
      properties:
        card_types:
          type: array
          items:
            $ref: '#/components/schemas/CardTypeEntity'
    ChargeCreateRequest:
      type: object
      properties:
        agreement_id:
          type: string
          description: Agreement ID to associate charge with
          example: md1mjge8gb6p4qndfs8mf8gto5
        amount:
          type: integer
          format: int64
          description: Amount in pence
          example: 100
          maximum: 10000000
          minimum: 0
        authorisation_mode:
          type: string
          description: Mode of authorisation for the payment. Payments created in
            `web` mode require the paying user to visit the `next_url` to complete
            the payment.
          enum:
          - web
          - moto_api
          - agreement
          - external
        delayed_capture:
          type: boolean
        description:
          type: string
          description: The payment description (shown to the user on the payment pages)
          example: payment description
          maximum: 255
        email:
          type: string
          example: joe.blogs@example.org
        language:
          type: string
          enum:
          - en
          - cy
          example: en
        metadata:
          $ref: '#/components/schemas/ExternalMetadata'
        moto:
          type: boolean
          description: Mail Order / Telephone Order (MOTO) payment flag
          example: true
        payment_provider:
          type: string
          description: Payment provider for the charge. Internal use only
          example: sandbox
        prefilled_cardholder_details:
          $ref: '#/components/schemas/PrefilledCardHolderDetails'
        reference:
          type: string
          description: The reference issued by the government service for this payment
          example: payment reference
          maximum: 255
        return_url:
          type: string
          description: The url to return the user to after the payment process has
            completed. Required when authorisation_mode is 'web'
          example: https://service-name.gov.uk/transactions/12345
        save_payment_instrument_to_agreement:
          type: boolean
          description: Applicable for recurring card payments. Indicated whether the
            payment method should be saved to agreement
        source:
          type: string
          description: Source of payment (e.g. CARD_PAYMENT_LINK) - defaults to CARD_API
            (which cannot be specified explicitly).
          enum:
          - CARD_API
          - CARD_PAYMENT_LINK
          - CARD_AGENT_INITIATED_MOTO
          - CARD_EXTERNAL_TELEPHONE
          example: CARD_API
      required:
      - amount
      - description
      - reference
    ChargeResponse:
      type: object
      properties:
        agreement_id:
          type: string
          description: 'Application for Recurring card payments. Agreement ID that
            the payment is associated with '
          example: md1mjge8gb6p4qndfs8mf8gto5
        amount:
          type: integer
          format: int64
          description: Amount of this charge
          example: 100
        auth_3ds_data:
          $ref: '#/components/schemas/Auth3dsData'
        auth_code:
          type: string
          description: Only applicable for telephone payments reported. Authorisation
            ID received from payment provider when the payment was authorised
          example: "91011"
        authorisation_mode:
          type: string
          default: web
          description: How the payment will be authorised. Payments created in `web`
            mode require the paying user to visit the `next_url` to complete the payment.
          enum:
          - web
          - moto_api
          - agreement
          - external
          example: web
        authorisation_summary:
          $ref: '#/components/schemas/AuthorisationSummary'
        authorised_date:
          type: string
          format: date-time
          description: 'Only applicable for telephone payments reported. Date and
            time Payment service provider authorised the payment. '
          example: 2022-06-28T16:05:33Z
        card_brand:
          type: string
          example: Visa
        card_details:
          $ref: '#/components/schemas/PersistedCard'
        charge_id:
          type: string
          description: Unique identifier for the charge
          example: b02b63b370fd35418ad66b0101
        corporate_card_surcharge:
          type: integer
          format: int64
        created_date:
          type: string
          format: date-time
          example: 2022-06-28T09:24:45.715Z
        delayed_capture:
          type: boolean
          description: "Set to true, if payment is to be captured separately"
        description:
          type: string
          description: The payment description
          example: payment description
        email:
          type: string
          example: Joe.Bogs@example.org
        fee:
          type: integer
          format: int64
          description: "processing fee taken by the GOV.UK Pay platform, in pence.\
            \ Only available depending on payment service provider"
          example: 10
        gateway_transaction_id:
          type: string
          description: The reference number the payment gateway associated with the
            payment.
          example: 5422624d-12b1-4821-8b26-d0383ecf1602
        language:
          type: string
          description: The language of the user’s payment page.
          enum:
          - en
          - cy
          example: en
        links:
          type: array
          description: Array of relevant resource references related to this charge
          example:
          - href: https://connector.example.com/v1/api/charges/b02b63b370fd35418ad66b0101
            method: GET
            rel: self
          - href: https://frontend.example.com/charges/1?chargeTokenId=82347
            method: GET
            rel: next_url
          - href: https://connector.example.com//v1/api/accounts/1/charges/b02b63b370fd35418ad66b0101/refunds
            method: GET
            rel: refunds
          items:
            type: object
            additionalProperties:
              type: object
              description: Array of relevant resource references related to this charge
              example:
              - href: https://connector.example.com/v1/api/charges/b02b63b370fd35418ad66b0101
                method: GET
                rel: self
              - href: https://frontend.example.com/charges/1?chargeTokenId=82347
                method: GET
                rel: next_url
              - href: https://connector.example.com//v1/api/accounts/1/charges/b02b63b370fd35418ad66b0101/refunds
                method: GET
                rel: refunds
            description: Array of relevant resource references related to this charge
            example:
            - href: https://connector.example.com/v1/api/charges/b02b63b370fd35418ad66b0101
              method: GET
              rel: self
            - href: https://frontend.example.com/charges/1?chargeTokenId=82347
              method: GET
              rel: next_url
            - href: https://connector.example.com//v1/api/accounts/1/charges/b02b63b370fd35418ad66b0101/refunds
              method: GET
              rel: refunds
        metadata:
          $ref: '#/components/schemas/ExternalMetadata'
        moto:
          type: boolean
          description: Mail Order / Telephone Order (MOTO) payment flag
        net_amount:
          type: integer
          format: int64
          description: "amount including all surcharges and less all fees, in pence.\
            \ Available depending on payment service provider"
          example: 90
        payment_outcome:
          $ref: '#/components/schemas/PaymentOutcome'
        payment_provider:
          type: string
          description: The payment provider used for this transaction
          example: sandbox
        processor_id:
          type: string
          description: Only applicable for telephone payments reported. unique supplier
            internal reference number associated with the payment
          example: "12345"
        provider_id:
          type: string
          description: Only applicable for telephone payments reported. Gateway transaction
            ID
          example: "45678"
        reference:
          $ref: '#/components/schemas/ServicePaymentReference'
        refund_summary:
          $ref: '#/components/schemas/RefundSummary'
        return_url:
          type: string
          description: service return url
          example: https://service-name.gov.uk/transactions/12345
        settlement_summary:
          $ref: '#/components/schemas/SettlementSummary'
        state:
          $ref: '#/components/schemas/ExternalTransactionState'
        telephone_number:
          type: string
          description: Only applicable for telephone payments reported. User's telephone
            number
          example: +44000000000
        total_amount:
          type: integer
          format: int64
          description: "Amount your user paid in pence, including corporate card fees.\
            \ total_amount only appears if corporate card surcharge is applied to\
            \ the payment."
        wallet_type:
          type: string
          description: Indicates if the payment was completed using wallet payment
            (GOOGLE_PAY or APPLE_PAY)
          enum:
          - APPLE_PAY
          - GOOGLE_PAY
          example: APPLE_PAY
    ErrorResponse:
      type: object
      properties:
        error_identifier:
          type: string
          enum:
          - GENERIC
          - REFUND_NOT_AVAILABLE
          - REFUND_AMOUNT_AVAILABLE_MISMATCH
          - ZERO_AMOUNT_NOT_ALLOWED
          - MOTO_NOT_ALLOWED
          - CANCEL_CHARGE_FAILURE_DUE_TO_CONFLICTING_TERMINAL_STATE_AT_GATEWAY_CHARGE_STATE_FORCIBLY_TRANSITIONED
          - CANCEL_CHARGE_FAILURE_DUE_TO_CONFLICTING_TERMINAL_STATE_AT_GATEWAY_INVALID_STATE_TRANSITION
          - AUTH_TOKEN_INVALID
          - AUTH_TOKEN_REVOKED
          - ACCOUNT_NOT_LINKED_WITH_PSP
          - TELEPHONE_PAYMENT_NOTIFICATIONS_NOT_ALLOWED
          - AGREEMENT_NOT_FOUND
          - ONE_TIME_TOKEN_INVALID
          - ONE_TIME_TOKEN_ALREADY_USED
          - INVALID_ATTRIBUTE_VALUE
          - CARD_NUMBER_REJECTED
          - AUTHORISATION_API_NOT_ALLOWED
          - AUTHORISATION_REJECTED
          - AUTHORISATION_ERROR
          - AUTHORISATION_TIMEOUT
          - AGREEMENT_NOT_ACTIVE
          - MISSING_MANDATORY_ATTRIBUTE
          - UNEXPECTED_ATTRIBUTE
          - ACCOUNT_DISABLED
          example: GENERIC
        message:
          type: array
          items:
            type: string
            example: error message
        reason:
          type: string
          example: "Optional - ex: amount_not_available"
    ExternalMetadata:
      type: object
      example: "{\"property1\": \"value1\", \"property2\": \"value2\"}\""
      properties:
        metadata:
          type: object
          additionalProperties:
            type: object
    ExternalTransactionState:
      type: object
      description: A structure representing the current state of the payment in its
        lifecycle
      properties:
        code:
          type: string
          description: Error code for failed payments
          example: P0010
        finished:
          type: boolean
          example: true
        message:
          type: string
          description: Message describing erro code if Payment failed
          example: Payment method rejected
        status:
          type: string
          example: success
    FirstDigitsCardNumber:
      type: object
      description: The first 6 digits of the card the user paid with.
      example: 424242
    LastDigitsCardNumber:
      type: object
      description: The last 4 digits of the card the user paid with.
      example: 4242
    PaymentOutcome:
      type: object
      description: Only applicable for telephone payments reported. Outcome after
        the payment has been authorised with payment provider
      properties:
        code:
          type: string
          description: Error code
          example: P0010
        status:
          type: string
          example: failed
        supplemental:
          $ref: '#/components/schemas/Supplemental'
    PersistedCard:
      type: object
      properties:
        billing_address:
          $ref: '#/components/schemas/Address'
        card_brand:
          type: string
          example: Visa
        card_type:
          type: string
          enum:
          - CREDIT
          - DEBIT
          example: debit
        cardholder_name:
          type: string
          description: The cardholder name the user entered when they paid.
          example: Joe B
        expiry_date:
          $ref: '#/components/schemas/CardExpiryDate'
        first_digits_card_number:
          $ref: '#/components/schemas/FirstDigitsCardNumber'
        last_digits_card_number:
          $ref: '#/components/schemas/LastDigitsCardNumber'
    PrefilledAddress:
      type: object
      description: A structure representing the billing address of a card
      properties:
        city:
          type: string
          example: London
          maxLength: 255
          minLength: 0
        country:
          type: string
          example: GB
        county:
          type: string
          example: country
          maxLength: 255
          minLength: 0
        line1:
          type: string
          example: address line 1
          maxLength: 255
          minLength: 0
        line2:
          type: string
          example: address line 2
          maxLength: 255
          minLength: 0
        postcode:
          type: string
          example: AB1 2CD
          maxLength: 25
          minLength: 0
    PrefilledCardHolderDetails:
      type: object
      properties:
        billing_address:
          $ref: '#/components/schemas/PrefilledAddress'
        cardholder_name:
          type: string
          description: prefilled cardholder name
          example: Joe B
    RefundSummary:
      type: object
      description: Provides refund amount available and the amount that has already
        been submitted for refund
      properties:
        amount_available:
          type: integer
          format: int64
          description: Amount available for refund in pence
          example: 100
        amount_submitted:
          type: integer
          format: int64
          description: Amount submitted for refunds on this Payment in pence
          example: 0
        status:
          type: string
          description: Availability status of the refund
          example: available
        user_external_id:
          type: string
          description: User external ID issuing refund
          example: sk03k2pojvsojd1po2joij92pspodrkwpenl
    ServicePaymentReference:
      type: object
      description: Service reference for the payment
      example: payment reference
    SettlementSummary:
      type: object
      description: "Provides a settlement summary of the charge containing date and\
        \ time of capture, if present"
      properties:
        capture_submit_time:
          type: string
          description: Date and time capture request has been submitted. May be null
            if capture request was not immediately acknowledged by payment gateway.
          example: 2022-06-28T09:26:45.715Z
        capturedTime:
          type: string
          format: date-time
          writeOnly: true
        captured_date:
          type: string
          description: Date of the capture event
          example: 2022-06-28
    Supplemental:
      type: object
      properties:
        error_code:
          type: string
          example: E1234
        error_message:
          type: string
          example: The payment card does not exist
    TelephoneChargeCreateRequest:
      type: object
      properties:
        amount:
          type: integer
          format: int64
          description: Amount in pence
          example: 100
          maximum: 10000000
        auth_code:
          type: string
          description: Authorisation ID received from payment provider when the payment
            was authorised
          example: "91011"
          maxLength: 50
        authorised_date:
          type: string
          description: "Date and time when payment service provider authorised the\
            \ payment. Must be in ISO 8601-1 datetime format, including the time zone"
          example: 2022-06-28T16:05:33Z
          maxLength: 50
        card_expiry:
          $ref: '#/components/schemas/CardExpiryDate'
        card_type:
          type: string
          description: "card_type and must be one of the following strings: master-card,\
            \ visa, maestro, diners-club, american-express, jcb"
          example: debit
        created_date:
          type: string
          description: "Date and time the payment was initiated. Must be in ISO 8601-1\
            \ datetime format, including time zone "
          example: 2022-06-28T09:24:45.715Z
          maximum: 50
        description:
          type: string
          description: The payment description
          example: payment description
          maxLength: 255
        email_address:
          type: string
          description: user's email address
          example: Joe.Bogs@example.org
        first_six_digits:
          type: string
          description: First 6 digits of user's payment card
          example: "424242"
        last_four_digits:
          type: string
          description: Last 4 digits of user's payment card
          example: "4242"
        name_on_card:
          type: string
          description: user's name on the front of their payment card
          example: Joe B
        payment_outcome:
          $ref: '#/components/schemas/PaymentOutcome'
        processor_id:
          type: string
          description: unique supplier internal reference number associated with the
            payment
          example: "12345"
        provider_id:
          type: string
          description: Gateway transaction ID
          example: "45678"
        reference:
          type: string
          description: service payment reference
          example: payment reference
          maxLength: 255
        telephone_number:
          type: string
          description: user's telephone number
          example: +44000000000
          maxLength: 50
      required:
      - amount
      - description
      - payment_outcome
      - processor_id
      - provider_id
      - reference
    ThreeDSecure:
      type: object
      description: Object containing information about the 3D Secure authentication
        of the payment
      properties:
        required:
          type: boolean
          description: Flag indicating whether the payment required 3D Secure authentication.
          example: true
        version:
          type: string
          description: 3DS version used to authorise payment
          example: 2.1.0
